### ISSUE TITLE
hosting

### ISSUE THREAD

**Issue by karissa** [karissa/dathub#3]
where are we going to host this thing?

**Comment by almereyda** [comment]
> any ideas on that?

We from @ecobytes would love to offer initial reasonable free hosting (either VM, Docker or PaaS) for dathub. We're running root servers at the German company Hetzner. As it scales out, one can always still realign. But as I see now (reverse DNSing `dathub.org`) there's already a digitalocean VM, so maybe no need for community-based non-profit infrastructure?

`alpha.dathub.org` - regarding the milestone - would sound nice, don't you think?
